# NumPy
NumPy is an open source project aiming to enable numerical computing with Python. It is the fundamental package for scientific computing in Python and provides efficient storage and computation for multi-dimensional data arrays. Its efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science. This notebook outlines techniques for effectively loading, storing, and manipulating in-memory data in Python.

In [1]:
# Importing NumPY and looking its version
import numpy
numpy.__version__

'1.19.2'

In [2]:
# Importing NumPy with an alias ---it is a common practice to use alias to shorten the name 
import numpy as np

In [3]:
# We can look the documentation to red more about NumPy
np?

## Understanding Data Types

In [4]:
# printing range of values---- range() is a built-in function
x=range(5)
for n in x:
  print(n)

0
1
2
3
4


In [5]:
# Summing numbers less than 100
x = 0
for i in range(100):
    x += i

In [6]:
# Notice Python assigns data type for the variable, not declared
# Both range of values and the sum are'int' data types
type(x)

int

In [7]:
# List --- the data types of each element depends on each element
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L2 = [True, "2", 3.0, 4]
[type(item) for item in L2]

[bool, str, float, int]

In [61]:
# Converting a 'list' of values to 'array'
import array
L = list(range(10))
arr= array.array('i', L)  # the 'i' is a type code indicating the contents are integers
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Detail info on array.array
array.array??

In [11]:
# Creating Arrays from Python Lists
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [12]:
# Unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
# so the numbers in the array will be changed to float if there is a single float in the list
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
# Determining the type using 'dtype'
arr = np.array([1, 2, 3, 4], dtype='float32')  #  dtype can be: float64, int
arr

array([1., 2., 3., 4.], dtype=float32)

In [14]:
# Creating a length-10 integer array filled with zeros
arr0 = np.zeros(10, dtype=int)
arr0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Creating a length-10 integer array filled with ones
arr1 = np.ones(10, dtype=int)
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## NumPy Array Attributes

In [63]:
np.random.seed(0)  # seed for reproducibility

arr1 = np.random.randint(10, size=6)  # One-dimensional array
arr2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
arr3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [64]:
# Dimension, shape, and size of the array
print("arr3 ndim: ", arr3.ndim)
print("arr3 shape:", arr3.shape)
print("arr3 size: ", arr3.size)

arr3 ndim:  3
arr3 shape: (3, 4, 5)
arr3 size:  60


## The NumPy ndarray: A Multidimensional Array Object
N-dimensional array object or ndarray is one of the key features of NumPy; which is a fast, flexible container for large datasets in Python.

In [16]:
# Create a 3x6 floating-point array filled with ones 
X0 = np.zeros((3, 6))
X0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# Create a 3x5 floating-point array filled with ones 
X1 = np.ones((3, 5), dtype=float)
X1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 3x5 array filled with 3.14
Xpi = np.full((3, 5), 3.14)
Xpi

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
a2 = np.arange(0, 20, 2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# generate small array of data
data = np.random.randn(2, 3)
data

array([[ 1.12553734, -0.71988763,  0.25436381],
       [ 0.97120578, -1.01173594, -0.0733245 ]])

In [21]:
# Creating multi-dimentional array from a nested list
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# Type of the whole -- ndarray
type(arr2)

numpy.ndarray

In [23]:
# Checking type of elements in the ndarray
arr2.dtype

dtype('int32')

In [24]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

## Arithmetic with NumPy Arrays

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Basic Indexing and Slicing

In [30]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

5

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
# Inserting new elements
arr[5:8] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
# Higher dimesional array ---  3 x 3 array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]  # an array

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [42]:
# Multi-dimensional array ---  2 x 2 x 3 array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0] # will be 2 X 3 array --- Notice the slicing dimension compared to the above slicing

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# copy old value if you want to manupulate the array---variables change permanently when manupulated 
old_values = arr3d[0].copy() 

In [45]:
arr3d[0] = 42  # 
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
# Indexing with slices
arr  # using the above array

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [58]:
arr2d[-1]

array([7, 8, 9])

In [59]:
arr2d[2, -1]

9

In [60]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])