# NumPy
NumPy is an open source project aiming to enable numerical computing with Python. It is the fundamental package for scientific computing in Python and provides efficient storage and computation for multi-dimensional data arrays. Its efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science. This notebook outlines techniques for effectively loading, storing, and manipulating in-memory data in Python.

In [1]:
# Importing NumPY and looking its version
import numpy
numpy.__version__

'1.19.2'

In [2]:
# Importing NumPy with an alias ---it is a common practice to use alias to shorten the name 
import numpy as np

In [4]:
# We can look the documentation to red more about NumPy
np?

## Understanding Data Types

In [36]:
# printing range of values---- range() is a built-in function
x=range(5)
for n in x:
  print(n)

0
1
2
3
4


In [37]:
# Summing numbers less than 100
x = 0
for i in range(100):
    x += i

In [38]:
# Notice Python assigns data type for the variable, not declared
# Both range of values and the sum are'int' data types
type(x)

int

In [39]:
# List --- the data types of each element depends on each element
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
L2 = [True, "2", 3.0, 4]
[type(item) for item in L2]

[bool, str, float, int]

In [27]:
# Converting a 'list' of values to 'array'
import array
L = list(range(10))
A = array.array('i', L)  # the 'i' is a type code indicating the contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Detail info on array.array
array.array??

In [34]:
# Creating Arrays from Python Lists
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [35]:
# Unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
# so the numbers in the array will be changed to float if there is a single float in the list
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [66]:
# Determining the type using 'dtype'
arr = np.array([1, 2, 3, 4], dtype='float32')  #  dtype can be: float64, int
arr

array([1., 2., 3., 4.], dtype=float32)

In [49]:
# Creating a length-10 integer array filled with zeros
a0 = np.zeros(10, dtype=int)
a0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
# Creating a length-10 integer array filled with ones
a1 = np.ones(10, dtype=int)
a1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## The NumPy ndarray: A Multidimensional Array Object
N-dimensional array object or ndarray is one of the key features of NumPy; which is a fast, flexible container for large datasets in Python.

In [61]:
# Create a 3x6 floating-point array filled with ones 
X0 = np.zeros((3, 6))
X0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [62]:
# Create a 3x5 floating-point array filled with ones 
X1 = np.ones((3, 5), dtype=float)
X1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Create a 3x5 array filled with 3.14
Xpi = np.full((3, 5), 3.14)
Xpi

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [54]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
a2 = np.arange(0, 20, 2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
# generate small array of data
data = np.random.randn(2, 3)
data

array([[-0.05392341, -0.69063982,  0.51571084],
       [-0.57042849, -0.50616748, -2.94909001]])

In [58]:
# Creating multi-dimentional array from a nested list
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Type of the whole -- ndarray
type(arr2)

numpy.ndarray

In [60]:
# Checking type of elements in the ndarray
arr2.dtype

dtype('int32')

In [65]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

## Arithmetic with NumPy Arrays

In [67]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [69]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [71]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Basic Indexing and Slicing

In [72]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[5]

5

In [74]:
arr[5:8]

array([5, 6, 7])

In [76]:
# Inserting new elements
arr[5:8] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])